[tool.poetry]
name = "bankapp"
version = "0.1.0"
description = ""
authors = ["gwy15 <gwy15thu@gmail.com>"]

[[tool.poetry.source]]
name = "tuna-pypi"
url = "https://pypi.tuna.tsinghua.edu.cn/simpl"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^1.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
