name: Build Docker

on: [push, release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker build
        run: docker build . -t bankapp:${GITHUB_SHA}
      - name: Docker push
        if: ${{ github.event == 'release' }}
        run: |
          docker tag bankapp:${GITHUB_SHA} ccr.ccs.tencentyun.com/gwy15/bankapp:${GITHUB_REF}
          docker login --username=${{secrets.docker_user}} ccr.ccs.tencentyun.com/gwy15/gwy15 -p ${{ secrets.docker_pswd }}
          docker push ccr.ccs.tencentyun.com/gwy15/bankapp:${GITHUB_REF}
